name: ForceEnd
main: io.github.cats1337.Main
description: Force end battle
version: 0.0.1
api-version: 1.16
author: Cats

commands:
  forceend:
    description: Force end battle
    usage: /forceend
    aliases: [fe]